using System.Reflection;
[assembly: AssemblyTitle("HelloWorld_Project")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Augusta University")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("Creative Commons Attribution 4.0 International")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("2.0.0.0")]