author: <https://csci-1301.github.io/about#authors>
lang: en
keywords:       
    - Computer Science
    - Problem solving methods
    - Augusta University
    - Bachelor of Science
    - C# Programming language
