name: Build

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: chetan/git-restore-mtime-action@v2
    - name: Cache  💾
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          pandoc-3.2-1-amd64.deb
        key: ${{ runner.os }}-pip-
        restore-keys: ${{ runner.os }}-pip-
    - name: Setup Python 🐍
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Setup pandoc ⚙️
      run: |
        sudo apt-get update
        test -f pandoc-3.2-1-amd64.deb || wget https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-1-amd64.deb
        sudo dpkg -i pandoc-3.2-1-amd64.deb
        sudo apt-get install -y texlive texlive-xetex texlive-latex-extra lmodern librsvg2-bin fonts-symbola 
        pip install --upgrade pip
        pip install Pygments pandoc-include
    - name: Fetch previous version ⤵️
      run: |
        cd /home/runner/work/csci-1301.github.io/csci-1301.github.io/
        wget https://github.com/csci-1301/csci-1301.github.io/releases/download/latest/release.zip && unzip -q release.zip 
    - name: Build 🏗️
      run: make all
    - name: Deploy website 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages 
        folder: build
        clean: true
        single-commit: true
    - name: Create package 🎁
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        automatic_release_tag: "latest"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        draft: false
        files: build/release.zip
