name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cancel previous runs ⏹️
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Cache  💾
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          pandoc-2.19.2-1-amd64.deb
        key: ${{ runner.os }}-pip-
        restore-keys: ${{ runner.os }}-pip-
    - name: Setup Python 🐍
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Setup pandoc ⚙️
      run: |
        sudo apt-get update
        test -f pandoc-3.1.12.3-1-amd64.deb || wget https://github.com/jgm/pandoc/releases/download/3.1.12.3/pandoc-3.1.12.3-1-amd64.deb
        sudo dpkg -i pandoc-3.1.12.3-1-amd64.deb
        sudo apt-get install -y texlive texlive-xetex texlive-latex-extra lmodern librsvg2-bin fonts-symbola 
        pip install --upgrade pip
        pip install Pygments pandoc-include
    - name: Build 🏗️
      run: make all
    - name: Deploy website 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages 
        folder: build
        clean: true
        single-commit: true
    - name: Create package 🎁
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: "latest"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        draft: false
        files: build/release.zip
